web:
  build: ./web
  volumes:
    - "./web:/src/web"
  ports:
    - "3030:3000"
  links:
    - "cache:redis"
    - "db:mongodb"
  command: npm run start

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web

cache:
  image: redis

db:
  image: mongo:3.2.11
  volumes:
    - "./mongodb_data:/data/db"
  ports:
    - "27018:27017"
